### ISSUE TITLE
Expose coroutine scope in retry

### ISSUE THREAD

**Issue by bchildsSR** [michaelbull/kotlin-retry#4]
It would be helpful for logging to be able to access the coroutine scope inside of the retry function. For example being able to see:
```
    retry(limitAttempts(5)) {
        println(coroutineContext.retryStatus.attempt)
    }
```
thanks!

**Comment by michaelbull** [comment]
Hi, thanks for your feedback.

From what I see there should be nothing stopping you from doing this:

```kotlin
import com.github.michaelbull.retry.context.retryStatus
import com.github.michaelbull.retry.policy.limitAttempts
import kotlinx.coroutines.runBlocking
import kotlin.coroutines.coroutineContext

fun main() = runBlocking {
    example()
}

suspend fun example() {
    retry(limitAttempts(5)) {
        val attempt = coroutineContext.retryStatus.attempt
        println(attempt)

        if (attempt < 4) {
            throw Exception()
        }
    }
}
```

The example above prints:
```
0
1
2
3
4
````

**Comment by bchildsSR** [comment]
Hi, thank you for the prompt response!
It looks like what I was missing is that it has to be in a suspend function to work:
```
fun main() = runBlocking {
    retry(limitAttempts(5)) {
        println(coroutineContext.retryStatus.attempt)

        if (coroutineContext.retryStatus.attempt < 4) {
            throw Exception()
        }
    }
}
```
this throws an `java.lang.IllegalStateException: No RetryStatus in context`

**Comment by michaelbull** [comment]
That's because the `coroutineContext` you're using on line 3 is from the `CoroutineScope` which is part of the receiver of the `runBlocking` method.

This is the signature of `runBlocking`:

```kotlin
fun <T> runBlocking(
    context: CoroutineContext = EmptyCoroutineContext,
    block: suspend CoroutineScope.() -> T
): T
```

Notice how the `block` is called with a receiver of `CoroutineScope`? `CoroutineScope` itself has its own `coroutineContext`:

```kotlin
public interface CoroutineScope {
    public val coroutineContext: CoroutineContext
}
```

Therefore the `coroutineContext` you end up referencing in your example is that of the scope within the call to `runBlocking`. You can prove this by Ctrl+Clicking in Intellij on the `coroutineContext` variable and it takes you to the declaration of `CoroutineScope.coroutineContext`.

The actual one we want is the one defined in the `import kotlin.coroutines.coroutineContext`, i.e.

```kotlin
@SinceKotlin("1.3")
@Suppress("WRONG_MODIFIER_TARGET")
@InlineOnly
public suspend inline val coroutineContext: CoroutineContext
```

You can still avoid the need for a `suspend fun` by explicitly referencing the **correct** `coroutineContext`:

```kotlin
import com.github.michaelbull.retry.context.retryStatus
import com.github.michaelbull.retry.policy.limitAttempts
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    retry(limitAttempts(5)) {
        val attempt = kotlin.coroutines.coroutineContext.retryStatus.attempt
        println(attempt)

        if (attempt < 4) {
            throw Exception()
        }
    }
}
```

Hopefully this explanation helps you understand why the `coroutineContext` you were using didn't have the `RetryStatus` within it.

**Comment by bchildsSR** [comment]
ok great, thank you again!
