### ISSUE TITLE
Is throwing from a RetryPolicy supported?

### ISSUE THREAD

**Issue by glasser** [michaelbull/kotlin-retry#6]
I'm trying to adapt some existing inflexible retry code to use your library.

One thing we do is that in some cases our retry function throws a different exception than the wrapped code. eg, we say "retry if the exception is T; if we have given up after too many Ts, throw T1, but if an unexpected exception happened just throw it directly".

We can implement this by having a RetryPolicy that actually throws T1 instead of returning StopRetrying, and it appears to work in the current implementation. Is this something we can rely on?

**Comment by michaelbull** [comment]
I think this behaviour is fine to rely on, but isn't designed for. You're basically causing the exception to be thrown when the [retry policy is evaluated](https://github.com/michaelbull/kotlin-retry/blob/master/src/main/kotlin/com/github/michaelbull/retry/Retry.kt#L43), which skips the code beneath (including incrementing the attempts etc).

I would also suggest considering using the [retryResult](https://github.com/michaelbull/kotlin-retry/blob/master/src/main/kotlin/com/github/michaelbull/retry/RetryResult.kt#L29) function. This uses my other [kotlin-result](https://github.com/michaelbull/kotlin-result) library and functions on the Result monad instead of Throwables. As such, the Result monad can do things like map errors of type T1 to type T2 by calling result.map. It might be a bit more effort to convert your existing code to return Results instead of throwing Throwables, but it might be worth it in the long run.
